// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxZfZO_bksONRVGaZB28tcg0ssCaZraGg',
    appId: '1:1002296774120:web:64381299d0c46a8940285d',
    messagingSenderId: '1002296774120',
    projectId: 'fir-0915-ded60',
    authDomain: 'fir-0915-ded60.firebaseapp.com',
    storageBucket: 'fir-0915-ded60.firebasestorage.app',
    measurementId: 'G-LW574L0PCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmICSdmgHIrWwHiwHYNbIsoJ9mcU-nCUw',
    appId: '1:1002296774120:android:e803c80d4217b41740285d',
    messagingSenderId: '1002296774120',
    projectId: 'fir-0915-ded60',
    storageBucket: 'fir-0915-ded60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-I8QdkeIohNa5uuuGS9DGVHIT3pIpxLY',
    appId: '1:1002296774120:ios:20f14469aae5f34c40285d',
    messagingSenderId: '1002296774120',
    projectId: 'fir-0915-ded60',
    storageBucket: 'fir-0915-ded60.firebasestorage.app',
    iosBundleId: 'com.example.firebaseSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-I8QdkeIohNa5uuuGS9DGVHIT3pIpxLY',
    appId: '1:1002296774120:ios:20f14469aae5f34c40285d',
    messagingSenderId: '1002296774120',
    projectId: 'fir-0915-ded60',
    storageBucket: 'fir-0915-ded60.firebasestorage.app',
    iosBundleId: 'com.example.firebaseSample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxZfZO_bksONRVGaZB28tcg0ssCaZraGg',
    appId: '1:1002296774120:web:4f4fae8ea053029240285d',
    messagingSenderId: '1002296774120',
    projectId: 'fir-0915-ded60',
    authDomain: 'fir-0915-ded60.firebaseapp.com',
    storageBucket: 'fir-0915-ded60.firebasestorage.app',
    measurementId: 'G-9BS9D0XWQ8',
  );
}
